// <auto-generated />
using ExemplosEFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExemplosEFCore.Migrations
{
    [DbContext(typeof(ExemploEFCoreContext))]
    partial class ExemploEFCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExemplosEFCore.Estado", b =>
                {
                    b.Property<string>("SiglaEstado")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int>("IdRegiao");

                    b.Property<string>("NomeCapital")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("NomeEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("SiglaEstado");

                    b.HasIndex("IdRegiao");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("ExemplosEFCore.Regiao", b =>
                {
                    b.Property<int>("IdRegiao");

                    b.Property<string>("NomeRegiao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("IdRegiao");

                    b.ToTable("Regioes");
                });

            modelBuilder.Entity("ExemplosEFCore.Estado", b =>
                {
                    b.HasOne("ExemplosEFCore.Regiao", "Regiao")
                        .WithMany("Estados")
                        .HasForeignKey("IdRegiao")
                        .HasConstraintName("FK_Estado_Regiao");
                });
#pragma warning restore 612, 618
        }
    }
}
